### ISSUE TITLE
Unexpected rejection of input string or input grammar triggered by string insertion

### ISSUE THREAD

**Issue by cmsmcq** [GuntherRademacher/markup-blitz#10]
While preparing the description of issue #9, I experimented with a slightly simpler variant of the grammar given there, for which Markup Blitz unexpectedly rejects the input.

Consider the following grammar:
````
input = (A|B)*.
A = -'A', rs, a-list, stop.
B = -'B', rs, b-list, stop.
@a-list = name ++ rs.
@b-list = name ++ (rs, +#20).
name = [L]+.

-stop = os, -".", os.
-s = -[Zs; #09; #0A].
-rs = s+.
-os = s*.
````
The basic idea is that either A or B can be followed by a blank-delimited sequence of whitespace-delimited identifiers.  In the rule for *a-list*, the separating whitespace is lost; in the rule for *b-list*, the whitespace supplied in the input is replaced by a single blank.  At least, that is the intent.  On the input `A  x. A x  y  z. B  x. B x  y  z.`, MB reports:
````
<?xml version="1.0" encoding="utf-8"?>
<ixml xmlns:ixml="http://invisiblexml.org/NS" ixml:state="failed">Failed to parse input:
syntax error, found 'C'...
while expecting [#9..., '.']
at line 1, column 29:
...y  z.
...</ixml>
````

When the rule for *b-list* is replaced by `@b-list = name ++ (" ", +#20).` or by `@b-list = name ++ (s, +#20).`, Markup Blitz reports an exception:

> Exception in thread "main" java.lang.ClassCastException: class de.bottlecaps.markup.blitz.grammar.Insertion cannot be cast to class de.bottlecaps.markup.blitz.grammar.Alt (de.bottlecaps.markup.blitz.grammar.Insertion and de.bottlecaps.markup.blitz.grammar.Alt are in unnamed module of loader 'app')
	at de.bottlecaps.markup.blitz.transform.Generator$State.transitions(Generator.java:409)
	at de.bottlecaps.markup.blitz.transform.Generator.generate(Generator.java:121)
	at de.bottlecaps.markup.Blitz.generate(Blitz.java:62)
	at de.bottlecaps.markup.Blitz.main(Blitz.java:138)

In case it matters, on my system `java --version` returns the following:
````
$ java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing)
````

**Comment by GuntherRademacher** [comment]
Thanks a lot for reporting this as well.

This is caused by an insufficient check whether the insertion occurs at the end of a rule. The LR parser that Markup Blitz uses handles insertions in the context of a reduction. This requires that the BNF transformation ensures that insertions always occur at the end of the rule. In the general case, this is achieved by replacing the insertion with a new nonterminal that only has the insertion in its rule. However, the new nonterminal is unnecessary if the insertion is already at the end of a rule. When examining this situation, however, cases in which the insertion occurs within a repetition were overlooked. There it is initially at the end, but is then rearranged by the BNF transformation, which resolves the repetition.

Now fixed in 1.4-SNAPSHOT.
